config/routes.rb
GagCf::Application.routes.draw do
  
  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  resources :users
  resources :user_sessions

  get "welcome/index"

  resources :posts
  
    

  root :to => 'welcome#index'

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
  
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :photo, :titulo
  validates_presence_of :titulo, :extension

  #un post pertenece a un usuario
  belongs_to :user

  after_save :guardar_foto #se ejecuta despues de ciertas acciones en el modelo
                           #se guardan la extension y el titulo de la foto en la bd 
  FOTOS = File.join Rails.root, 'public', 'photo_store'
  #join crea una ruta, root hacer referencia a la carpeta donde se encuentre la app 
  #ex: /rails_code/gag_cf = Rails.root/public/photo_store

  def photo=(file_data)
  	unless file_data.blank?
  		@file_data=file_data
  		self.extension = file_data.original_filename.split('.').last.downcase
      #guarda la extension del archivo
  	end	

  end

  #va a crear el nombre del archivo que se va a crear
  def photo_filename
    File.join FOTOS, "#{id}.#{extension}"
    #ex: /gag_cf/public/photo_store/23.png
    #recordar todos los metodos en ruby retornan la ultima linea por defecto
  end

  def photo_path
    "/photo_store/#{id}.#{extension}"
  end

  #verifica si un archivo existe
  def has_photo?
    File.exists? photo_filename
  end

  private

  def guardar_foto
  	if @file_data
  		FileUtils.mkdir_p FOTOS  #Fileutils permite modificar y manipular archivos
  		File.open(photo_filename, 'wb') do |f|
  			f.write(@file_data.read)
  	    end
  	    @file_data = nil
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  # attr_accessible :title, :body
  attr_accessible :password, :password_confirmation, :email, :crypted_password, :salt

  #Un usuario posee muchos posts
  has_many :posts

  validates :email, uniqueness: true

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  #Variables virtuales 'password' y 'password_confirmation'
  #Debido a eso se utlizan getters and setters

  def password
    @crypted_password
   
  end
 
  def password_confirmation
    @salt
       
  end
 
  def password=(val)
    @crypted_password = val
  end
 
  def password_confirmation=(val)
    @salt = val
  end
	
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login
  
  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    @post.user_id=current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def find
    @user = User.new
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :require_login, except: [:destroy]

  def new
     @user = User.new	
  end

  def create
  	if @user = login(params[:email], params[:password])
  	  #'redirect_back_or_to' takes care of redirecting the
  	  # user to the page he asked for before reaching the login form, if such a page exists.
      redirect_back_or_to(:posts, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
  	logout
    redirect_to(:root, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login, only: [:index, :new, :create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to(:users, notice: 'User was successfully created')
    end
    
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

  #allow UsersController receive form attributes
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	before_filter :require_login, :only => :secret
	
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container bs-docs-container">
    <article>
      <header>
        <div class="page-header">
          <h1>Movies Barcelona <small>The best movies Titles</small></h1>
        </div>
      </header>
    </article>  
    <!-- bootstrap -->
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Index', root_path %></li>
            <li><%= link_to 'Movies', posts_path %></li>
            <% if current_user %>
              <li><%= link_to 'New Movie', new_post_path %></li>
              <li><%= link_to 'logout=> '+current_user.email, logout_path %></li>
              <li><%= link_to 'Edit user', edit_user_path(current_user) %></li>
            <% else %>
              <li><%= link_to "Sign Up", new_user_path %></li>
              <li><%= link_to 'Sign In', login_path %></li>
            <%end%>  
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <br>
    <footer>
      <div class="navbar navbar-inverse">
        <div class="panel-footer">Posted by: Julian Diaz</div>
      </div>
    </footer>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="row show-grid" id='post'>
  <%= form_for @post, :html => { :multipart => true } do |f| %>
    <!-- html: {multipart: true} necesario para subir una imagen-->
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class='col-xs-6 col-md-4'>
        <% if @post.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="input-group input-group-lg">
          <%= f.label :titulo %>
          <%= f.text_field :titulo %>
        </div>
        <br>
        <!--file_field control para subir imagenes-->
        <div class="input-group input-group-lg">
          <%= f.label :photo %>
          <%= f.file_field :photo %>
        </div>
        <br><br>
        <div class="input-group input-group-lg">
          <%= f.submit class: 'btn btn-default' %>
        </div>  
      </div>  
    </div>
    <div class="col-md-4"></div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="row show-grid" id='post'>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class='col-xs-8 col-md-10'>
      <div class="input-group input-group-lg">
        <h1>Editing Movie</h1>  
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>          
</div>
<br>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="container">
  <h1>Listing movies</h1>
  <br>	
  <div class="row" id='post'>
  	<div class="col-md-9" role="main">
      <div class="row show-grid">
        <% @posts.each do |post| %>
          <div class='col-xs-6 col-md-3'>
            <div class="thumbnail">	
        	    <% if post.has_photo? %>
        	      <%= image_tag post.photo_path %>
        	    <% end%>
        	    <div class='caption'>
        	      <p><%= link_to post.titulo, post %></p>
                <p><%= link_to "Update",edit_post_path(post), class: "btn btn-primary"%> <%= link_to "Delete",post, method: :delete, class: "btn btn-default", data: {:confirm => 'Are you sure?'} %> <!-- link_to con multiples opciones OJO-->
                </p> 
        	    </div>
        	  </div>      
          </div>
        <%end%>
      </div>  
    </div>    
  </div>
</div>
<br />

app/views/posts/new.html.erb
<div class="row show-grid" id='post'>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class='col-xs-6 col-md-8'>
      <div class="input-group input-group-lg">
        <h1>New Movie</h1>  
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>          
</div>
<br>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="container">
  <div class="row" id='post'>
  	<p id="notice"><%= notice %></p>

  	<p>
  	  <b>Title:</b>
  	  <%= @post.titulo %>
  	</p>

  	<p>
  	  <% if @post.has_photo? %> 
  	  	<!-- metodo auxiliar para las imagenes-->
  	  	<%= image_tag @post.photo_path %>
  	  <% else %>
  	  	<b>Problem in upload process</b>
  	  <% end %>  	
  	</p>
  </div>
</div>
<br />

app/views/user_sessions/_form.html.erb
<div class="row show-grid" id='post'>
  <%= form_tag user_sessions_path, :method => :post do %>
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class='col-xs-6 col-md-4'>
        <div class="input-group input-group-lg">
          <span>
            <%= label_tag :email %>
            <%= text_field_tag :email %>
          </span>
        </div>
        <div class="input-group input-group-lg">
          <span>
            <%= label_tag :password %>
            <%= password_field_tag :password %>
          </span>
        </div>
        <br>
        <div class="input-group input-group-lg">
          <span>
            <%= submit_tag "Login", class: "btn btn-default" %>
          </span>
        </div>
      </div>
      <br>
    </div>
    <div class="col-md-4"></div>          
  <% end %>
</div>
<br>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="row show-grid" id='post'>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class='col-xs-6 col-md-4'>
      <div class="input-group input-group-lg">
        <h1>Login</h1>  
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>          
</div>
<br>

<%= render 'form' %>

app/views/users/_form.html.erb
<div class="row show-grid" id='post'>
  <%= form_for(@user) do |f| %>
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class='col-xs-6 col-md-4'>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="input-group input-group-lg">
          <span>
            <%= f.label :email %>
            <%= f.text_field :email %>
          </span>
        </div>
        <div class="input-group input-group-lg">
          <span>
            <%= f.label :password %>
            <%= f.password_field :password %>
          </span>
        </div>
        <div class="input-group input-group-lg">
          <span>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation %>
          </span>
        </div>
        <br>
        <div class="input-group input-group-lg">
          <span>
            <%= f.submit class: 'btn btn-default'%>
          </span>
        </div>
      </div>
    </div>
    <div class="col-md-4"></div>
  <% end %>
</div>
<br>


    
    

app/views/users/edit.html.erb
<div class="row show-grid" id='post'>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class='col-xs-6 col-md-8'>
      <div class="input-group input-group-lg">
        <h1>Editing User</h1>  
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>          
</div>
<br>

<%= render 'form' %>

app/views/users/index.html.erb
<style>
table, td, th {
    border: 1px solid black;
}

table {
    width: 40%;
}

th {
    height: 25px;
}
td {
    padding: 15px;
}
</style>
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row show-grid" id='post'>
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class='col-xs-8 col-md-8'>
      <div class="input-group input-group-lg">
        <h1>New User</h1>  
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>          
</div>
<br>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
  <div class="row" id='post'>
    <p id="notice"><%= notice %></p>

    <p>
      <b>Email:</b>
      <%= @user.email %>
    </p>

    <p>
      <b>Crypted password:</b>
      <%= @user.crypted_password %>
    </p>

    <p>
      <b>Salt:</b>
      <%= @user.salt %>
    </p>
  </div>
</div>
<br />

app/views/welcome/index.html.erb
<div class="page-header">
  <div class="jumbotron">
    <h1>Hello, Movie Geeks!</h1>
    <p>Here you can easily add, remove and update movies titles with his according image. </p>
    <p><%= link_to "Register",new_user_path, { :class=>"btn btn-primary btn-lg" } %></p>
  </div>
</div>